package Ejercicio9_Productos;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Ejercicio9_Productos extends javax.swing.JFrame {

    private ArrayList<Producto> almacen; //almacén de productos

    public Ejercicio9_Productos() {
        initComponents();
        setFrame();
        almacen = new <Producto>ArrayList();
        cargarCombo();
        crearProductos();
    }

    private void setFrame() {
        this.setMinimumSize(new Dimension(400, 300));
        this.setPreferredSize(new Dimension(400, 300));
        this.pack();
        this.setLocationRelativeTo(null);
    }

    public void cargarCombo() {
        String[] tipos = {"(elija uno)", "A", "B", "C"};
        this.jComboBox1.setModel(new DefaultComboBoxModel(tipos));
    }

    public void crearProductos() {
        Producto p1 = new Producto("A", 1, "Producto1");
        p1.setPrecio(5.0);
        p1.setCantidad(10);
        Producto p2 = new Producto("A", 2, "Producto2");
        p2.setPrecio(0.5);
        p2.setCantidad(15);
        Producto p3 = new Producto("C", 3, "Producto3");
        p3.setPrecio(7.0);
        p3.setCantidad(5);
        Producto p4 = new Producto("A", 4, "Producto4");
        p4.setPrecio(35.0);
        p4.setCantidad(22);

        almacen.add(p1);
        almacen.add(p2);
        almacen.add(p3);
        almacen.add(p4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio9");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tipo de producto:");
        jPanel1.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de productos"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SELECCIÓN DE UN ELEMENTO DEL COMBO
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (this.jComboBox1.getSelectedIndex() != 0) { //si se ha elegido un tipo de producto
            //cargamos en la lista los productos del tipo elegido
            String tipo = String.valueOf(this.jComboBox1.getSelectedItem());
            //cargamos un arrayList con los prodcutos de ese tipo
            ArrayList<Producto> listaProductos = buscarProductos(tipo);
            this.jList1.setListData(listaProductos.toArray());
        } else {
            this.jList1.setListData(new Object[]{});
//            this.jList1.setModel(new javax.swing.DefaultListModel());
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    //Método que devuelve un arrayList con los productos
    //del tipo recibido como parámetro
    public ArrayList buscarProductos(String tipo) {
        ArrayList l = new ArrayList();
        for (Producto p : almacen) {
            if (p.getTipo().equals(tipo)) {
                l.add(p);
            }
        }
        return l;
    }

    //SE SELECCIONA UN ELEMENTO DE LA LISTA
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (this.jList1.getSelectedValue() != null) {  //si se ha elegido un elemento de la lista
            Producto p = (Producto) this.jList1.getSelectedValue(); //Producto seleccionado
            int codigo = p.getCodigo();
            int cantidad = p.getCantidad();
            if (cantidad >= 10) {
                JOptionPane.showMessageDialog(this, "Nº de unidades: " + cantidad, "Stock en almacén", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Nº de unidades: " + cantidad + "\nDebajo del stock de seguridad", "Stock en almacén", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_jList1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio9_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio9_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio9_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio9_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ejercicio9_Productos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
