package Ejercicio7_Etiquetas;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class Ejercicio7_Etiquetas extends javax.swing.JFrame {

    private JLabel etiqueta;
    
    public Ejercicio7_Etiquetas() {
        initComponents();
        
        this.setTitle("Ejercicio7");
        this.setPreferredSize(new Dimension(400, 300));
        this.setState(JFrame.ICONIFIED);
        this.getContentPane().setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.pack();
        this.setLocationRelativeTo(null);
        setEtiquetas();        
        mostrarInformacion();
    }

    private void setEtiquetas() {
        this.jPanel1.setBackground(Color.WHITE);
        for (int i = 0; i < 5; i++) {
            etiqueta=new JLabel("Etiqueta" + i);
            etiqueta.setName("Etiqueta" + i); 
            etiqueta.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 5));
            etiqueta.setFont(new Font("Tahoma",Font.ITALIC, 30));
            this.jPanel1.add(etiqueta);
        }        
    }

    public void mostrarInformacion() {
        System.out.println("Nombre ventana: " + this.getName());
        System.out.println("\tDimensiones: " + this.getWidth() + " X " + this.getHeight());
        System.out.println("\tPosición : (x,y) = (" + this.getX() + "," + this.getY());
        System.out.println("\tColor de fondo: " + this.jPanel1.getBackground().toString());
        System.out.println("\tColor de fuente: " + this.jPanel1.getForeground().toString());
        System.out.println("\tComponente padre: " + this.getParent());
        System.out.println("Controles que contiene... ");

        for (int i = 0; i < this.jPanel1.getComponentCount(); i++) {
            System.out.print("\tTipo: " + this.jPanel1.getComponent(i).getClass());
            System.out.println("  Nombre: " + this.jPanel1.getComponent(i).getName());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(1, 10, 10));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7_Etiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7_Etiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7_Etiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7_Etiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ejercicio7_Etiquetas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
