package Ejercicio10_Polinomio;

import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class Ejercicio10_Polinomio extends javax.swing.JFrame 
     {

    private Integer a;
    private Integer b;
    private Integer c;
    private final int MAX = 100;
    private final int MIN = -100;
    private boolean pulsadoEnter = false;

    public Ejercicio10_Polinomio() {
        initComponents();
        setFrame();        
    }

    private void setFrame() {
        this.setLocationRelativeTo(null);
        a = b = 1;
        c = 0;
        jSlider1.setValue(a);
        jSlider2.setValue(b);
        jSlider3.setValue(c);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(32767, 0));
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(32767, 0));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio10");
        setMinimumSize(new java.awt.Dimension(430, 250));
        setPreferredSize(new java.awt.Dimension(430, 250));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler1);

        jButton1.setMnemonic('C');
        jButton1.setText("Calcular raices");
        jButton1.setPreferredSize(new java.awt.Dimension(300, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jPanel2.add(filler2);

        jPanel1.add(jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("a");
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel3.add(jLabel1);

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinimum(-100);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintTicks(true);
        jSlider1.setPreferredSize(new java.awt.Dimension(300, 23));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel3.add(jSlider1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(40, 30));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1);

        jPanel1.add(jPanel3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("b");
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel4.add(jLabel2);

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setMinimum(-100);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setPaintTicks(true);
        jSlider2.setPreferredSize(new java.awt.Dimension(300, 23));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel4.add(jSlider2);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setOpaque(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(40, 30));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel4.add(jTextField2);

        jPanel1.add(jPanel4);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("c");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel5.add(jLabel3);

        jSlider3.setMajorTickSpacing(20);
        jSlider3.setMinimum(-100);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setPaintTicks(true);
        jSlider3.setPreferredSize(new java.awt.Dimension(300, 23));
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        jPanel5.add(jSlider3);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setOpaque(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(40, 30));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField3);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        a = jSlider1.getValue();
        jTextField1.setText(String.valueOf(a));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        b = jSlider2.getValue();
        jTextField2.setText(String.valueOf(b));
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        c = jSlider3.getValue();
        jTextField3.setText(String.valueOf(c));
    }//GEN-LAST:event_jSlider3StateChanged

    //BOTÓN CALCULAR RAICES
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIResultados result = new GUIResultados(this, true);
        result.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //DOBLE CLIC EN 'A'
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if (evt.getClickCount() == 2) {
            habilitar(evt);
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    //ENTER EN 'A'
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pulsadoEnter = true;
            asignarValor(this.jSlider1,(JTextField)evt.getSource(),this.a);
            this.jTextField1.select(0, 0);
            deshabilitar(evt);
            pulsadoEnter = false;
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    //SALIR DE 'A'
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (!pulsadoEnter) {
            this.jTextField1.setText(String.valueOf(a));
        }
        deshabilitar(evt);
    }//GEN-LAST:event_jTextField1FocusLost

    //DOBLE CLIC EN 'B'
    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        if (evt.getClickCount() == 2) {
            habilitar(evt);
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    //ENTER EN 'B'
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pulsadoEnter = true;
            asignarValor(this.jSlider2,(JTextField)evt.getSource(),this.b);
            this.jTextField2.select(0, 0);
            deshabilitar(evt);
            pulsadoEnter = false;
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    //SALIR DE 'B'
    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if (!pulsadoEnter) {
            this.jTextField2.setText(String.valueOf(b));
        }
        deshabilitar(evt);
    }//GEN-LAST:event_jTextField2FocusLost

    //DOBLE CLIC EN 'C'
    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        if (evt.getClickCount() == 2) {
            habilitar(evt);
        }
    }//GEN-LAST:event_jTextField3MouseClicked

    //ENTER EN 'C'
    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pulsadoEnter = true;
            asignarValor(this.jSlider3,(JTextField)evt.getSource(),this.c);
            this.jTextField3.select(0, 0);
            deshabilitar(evt);
            pulsadoEnter = false;
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    //SALIR DE 'C'
    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        if (!pulsadoEnter) {
            this.jTextField3.setText(String.valueOf(c));
        }
        deshabilitar(evt);
    }//GEN-LAST:event_jTextField3FocusLost

    private void deshabilitar(AWTEvent evt) {
        ((JTextField) evt.getSource()).setEditable(false);
        ((JTextField) evt.getSource()).setBackground(new Color(204, 204, 204));
    }

    private void habilitar(java.awt.event.InputEvent evt) {
        ((JTextField) evt.getSource()).setEditable(true);
        ((JTextField) evt.getSource()).setBackground(Color.WHITE);
    }

    private boolean esValido(String dato) {
        try {
            int n = Integer.parseInt(dato);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    private void asignarValor(JSlider slider,JTextField caja, Integer coef) {
        if (esValido(caja.getText())) {
            int valor = Integer.parseInt(caja.getText());
            if (valor > MAX) {
                coef = MAX;
            } else if (valor < MIN) {
                coef = MIN;
            } else {
                coef = Integer.parseInt(caja.getText());
            }
            slider.setValue(coef);
            caja.setText(String.valueOf(coef));
        } else {
            caja.setText(String.valueOf(coef));
        }
    }

    public int getA() {
        return a;
    }

    public int getB() {
        return b;
    }

    public int getC() {
        return c;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio10_Polinomio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio10_Polinomio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio10_Polinomio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio10_Polinomio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio10_Polinomio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
}
