package Soluciones;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.EOFException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box.Filler;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.text.StyleConstants;

public class Ejercicio6_Fichero extends javax.swing.JFrame implements KeyListener {

    private File fich;
    private String ruta = "src/Ficheros/participantes.obj";
    private FileOutputStream fos = null;
    private ObjectOutputStream oos = null;

    public Ejercicio6_Fichero() {
        initComponents();
        setFrame();
        abrirConexion();
    }

    public void setFrame() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);//desactivar aspa de cierre
        Dimension d = new Dimension(30, 30);
        this.getContentPane().add(new Filler(d, d, d), BorderLayout.LINE_START);
        this.getContentPane().add(new Filler(d, d, d), BorderLayout.LINE_END);
        this.getContentPane().add(new Filler(d, d, d), BorderLayout.PAGE_START);
        this.getContentPane().add(new Filler(d, d, d), BorderLayout.PAGE_END);
        this.pack();
        setLocationRelativeTo(null);
        setTeclas(this.getContentPane());
    }

    private void setTeclas(Container contenedor) {
        Component[] componentes = contenedor.getComponents();
        for (Component c : componentes) {
            if (c instanceof Container) {
                setTeclas((Container) c);
            }
            c.addKeyListener(this);
        }
    }

    private void abrirConexion() {
        try {
            fich = new File(ruta);
            fos = new FileOutputStream(fich,true); //Abrimos el fichero en modo APPEND
            oos = new ObjectOutputStream(fos);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ejercicio6_Fichero.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ejercicio6_Fichero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cerrarConexion() {
        try {
            if (fos != null) {
                fos.close();
            }
            if (oos != null) {
                oos.close();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(32767, 0));
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(32767, 0));
        jPanel5 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(32767, 0));
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(32767, 0));
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio6");
        setMinimumSize(new java.awt.Dimension(500, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de participantes");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(filler4);

        jLabel2.setText("Nombre:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 16));
        jPanel3.add(jLabel2);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jPanel3.add(jTextField1);
        jPanel3.add(filler1);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler5);

        jLabel3.setText("Edad:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 16));
        jPanel4.add(jLabel3);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyPressed(evt);
            }
        });
        jPanel4.add(jFormattedTextField1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel4);
        jPanel4.add(filler7);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(filler6);

        jLabel5.setText("Dirección:");
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 14));
        jPanel5.add(jLabel5);

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jPanel5.add(jTextField3);
        jPanel5.add(filler2);

        jPanel1.add(jPanel5);

        jPanel6.setMinimumSize(new java.awt.Dimension(5, 5));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 1));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));
        jPanel8.add(filler9);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jPanel8.add(jSeparator1);
        jPanel8.add(filler8);

        jPanel6.add(jPanel8);

        jPanel7.setLayout(new java.awt.FlowLayout(2));

        jButton1.setMnemonic('A');
        jButton1.setText("Aceptar");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setMnemonic('C');
        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel7.add(jButton2);
        jPanel7.add(filler3);

        jPanel6.add(jPanel7);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //NOMBRE RECIBE EL FOCO
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        this.jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1FocusGained

    //EDAD RECIBE EL FOCO
    private void jFormattedTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusGained
        this.jFormattedTextField1.selectAll();
    }//GEN-LAST:event_jFormattedTextField1FocusGained
    
    //DIRECCIÓN RECIBE EL FOCO
    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        this.jTextField3.selectAll();
    }//GEN-LAST:event_jTextField3FocusGained

    //EDAD PIERDE EL FOCO
    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
        if (!this.jFormattedTextField1.getText().equals("")) {
            try {
                int edad = Integer.parseInt(this.jFormattedTextField1.getText());
                if (edad < 4) {
                    JOptionPane.showMessageDialog(this, "La edad no puede ser inferior a 4 años", "Error", JOptionPane.ERROR_MESSAGE);
                    this.jFormattedTextField1.requestFocusInWindow(); //pide el foco
                    this.jFormattedTextField1.selectAll(); //se selecciona su contenido
                    this.jLabel4.setText(""); //limpio por si había algo de antes               
                } else if (!this.jLabel4.getText().equals("")) {
                    //comprobamos que la categoría es de la edad actual
                    if (!this.jLabel4.getText().equals(categoria(edad))) {
                        //si no coinciden, borro la categoria, porque es anterior
                        this.jLabel4.setText("");
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "La edad debe ser numérica", "Error", JOptionPane.ERROR_MESSAGE);
                this.jFormattedTextField1.requestFocusInWindow(); //pide el foco
                this.jFormattedTextField1.selectAll(); //se selecciona su contenido

            }
        }
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    private String categoria(int edad) {
        try {
            if (edad >= 4 && edad < 10) {
                return "Infantil";
            } else if (edad >= 10 && edad < 16) {
                return "Alevín";
            } else if (edad >= 16 && edad < 20) {
                return "Juvenil";
            } else if (edad >= 20) {
                return "Amateur";
            } else {
                return "";
            }
        } catch (NumberFormatException e) {
            return "";
        }

    }
    
    //F1 EN LA EDAD
    private void jFormattedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyPressed
        int codTecla = evt.getKeyCode();
        if (codTecla == KeyEvent.VK_F1) {
            int edad = Integer.parseInt(this.jFormattedTextField1.getText());
            if (edad >= 4) { //Solo si la edad es correcta
                this.jLabel4.setText(categoria(edad));
            }
        } else {
            this.jLabel4.setText(""); //limpio por si había algo antes
        }
    }//GEN-LAST:event_jFormattedTextField1KeyPressed

    //BOTÓN ACEPTAR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nom = this.jTextField1.getText();
            String sEdad = this.jFormattedTextField1.getText();
            int edad = sEdad.equals("") ? 0 : Integer.parseInt(sEdad);
            String direc = this.jTextField3.getText();
            Participante p = new Participante(nom, edad, direc);
            grabarParticipante(p);
            JOptionPane.showMessageDialog(this, "Participante almacenado", "Información", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            this.jTextField1.requestFocus();
        } catch (Exception e) {
            int err = Integer.parseInt(e.getMessage());
            if (err == 1) {
                JOptionPane.showMessageDialog(this, "Error. Participante sin nombre", "Error", JOptionPane.ERROR_MESSAGE);
                this.jTextField1.requestFocus();
            } else if (err == 2) {
                JOptionPane.showMessageDialog(this, "Error. Participante sin edad", "Error", JOptionPane.ERROR_MESSAGE);
                this.jFormattedTextField1.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //BOTÓN CANCELAR
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    //ENTER EN BOTÓN ACEPTAR
    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    //ENTER EN BOTÓN CANCELAR
    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jButton2.doClick();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    //AL CERRAR LA VENTANA
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        cerrarConexion();        
    }//GEN-LAST:event_formWindowClosed

    private void grabarParticipante(Participante p) {
        try {
            oos.writeObject(p);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    //LIMPIAR LAS CAJAS DE TEXTO
    private void limpiar() {
        this.jTextField1.setText("");
        this.jFormattedTextField1.setText("");
        this.jTextField3.setText("");
        this.jLabel4.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6_Fichero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6_Fichero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6_Fichero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6_Fichero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio6_Fichero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {

    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Abandonar la aplicación?");
            if (resp == JOptionPane.YES_OPTION) {
                this.formWindowClosed(null);
                //cerrarConexion();
                System.exit(0);
            }
        }
    }
}
