package Soluciones;

import java.awt.Dimension;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Date;

public class GUI_Resultados extends javax.swing.JDialog {

    private GUI_Encuesta ventanaPpal; //referencia a la ventana inicial

    public GUI_Resultados(GUI_Encuesta v, boolean modal) {
        super(v, modal);
        initComponents();
        setFrame();
        setPanel();
        this.ventanaPpal = v;
        mostrarResumen();
    }

    private void setFrame() {
        this.setMinimumSize(new Dimension(420, 210));
        this.setPreferredSize(new Dimension(420, 210));
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(this.ventanaPpal);
    }

    private void setPanel() {
        this.jEditorPane1.setContentType("text/html");
    }

    private void mostrarResumen() {
        NumberFormat formateadorNum = NumberFormat.getPercentInstance(); //multiplica por 100 y añade %
        formateadorNum.setMaximumFractionDigits(2); //máximo 2 decimales
        DateFormat formateadorFech = DateFormat.getDateInstance();
        DateFormat formateadorHora = DateFormat.getTimeInstance();
        double totalVotos = this.ventanaPpal.getVotos();
        double totalOpc1 = (totalVotos == 0) ? 0 : (double) this.ventanaPpal.getOpc1() / totalVotos;
        double totalOpc2 = (totalVotos == 0) ? 0 : (double) this.ventanaPpal.getOpc2() / totalVotos;
        double totalOpc3 = (totalVotos == 0) ? 0 : (double) this.ventanaPpal.getOpc3() / totalVotos;
        double totalOpc4 = (totalVotos == 0) ? 0 : (double) this.ventanaPpal.getOpc4() / totalVotos;
        this.jEditorPane1.setText(
                "<b>Fecha: " + formateadorFech.format(new Date()) + "</b><br>" +
                "<b>Hora: " + formateadorHora.format(new Date()) + "</b><br><br>" +
                "A favor del " + this.ventanaPpal.getjRadioButton1().getText() + " : " + formateadorNum.format(totalOpc1) + "<br>" + 
                "A favor del " + this.ventanaPpal.getjRadioButton2().getText() + " : " + formateadorNum.format(totalOpc2) + "<br>" +  
                "A favor del " + this.ventanaPpal.getjRadioButton3().getText() + " : " + formateadorNum.format(totalOpc3) + "<br>" +  
                "Otra opción : " + this.ventanaPpal.getjRadioButton4().getText() + " : " + formateadorNum.format(totalOpc4)+ "<br><br>" + 
                "<font size=\"14\" color=\"blue\">" + 
                    "<i>Gracias por tu colaboración!!</i>" + 
                "</font><br>"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultados encuesta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.ventanaPpal.ventanaResult = null;
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
