package Ejercicio10_Polinomio;

import java.text.DecimalFormat;

public class GUIResultados extends javax.swing.JDialog {

    private Ejercicio10_Polinomio ppal;

    public GUIResultados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ppal = (Ejercicio10_Polinomio) parent;
        initComponents();
        this.setLocationRelativeTo(parent);
        calcularRaices();
    }

    private void calcularRaices() {

        //recogemos los valores de los coeficientes        
        double a = this.ppal.getA();
        double b = this.ppal.getB();
        double c = this.ppal.getC();

        //cambiamos el titulo de la ventana
        String sb = (b >= 0) ? " + " : " ";
        String sc = (c >= 0) ? " + " : " ";
        this.setTitle("Polinomio " + (int) a + "x2" + sb + (int) b + "x" + sc + (int) c);

        //mostramos el resultado
        double discr = b * b - 4 * a * c;

        DecimalFormat df = new DecimalFormat("0.0000");

        if (discr < 0) { //raices imaginarias
            this.jLabel1.setText("Raices imaginarias");
            this.jLabel2.setText("r1= " + ((-1) * b / 2 * a) + "+i" + (Math.sqrt(discr) / 2 * a));
            this.jLabel3.setText("r2= " + ((-1) * b / 2 * a) + "-i" + (Math.sqrt(discr) / 2 * a));
        } else if (discr > 0) {
            this.jLabel1.setText("Raices reales");
            this.jLabel2.setText("r1= " + df.format(((-1) * b + Math.sqrt(discr)) / 2 * a));
            this.jLabel3.setText("r2= " + df.format((((-1) * b - Math.sqrt(discr)) / 2 * a)));
        } else { //discrimiante igual a 0 (raices iguales)
            this.jLabel1.setText("Raices reales iguales");
            this.jLabel2.setText("r= " + ((-1) * b / 2 * a));
            this.jLabel3.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Raices del polinomio de 2º grado");
        setMinimumSize(new java.awt.Dimension(300, 150));
        setPreferredSize(new java.awt.Dimension(300, 150));
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
